services:
  website:
    build: ./website
    volumes:
      - ./website:/app
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - VIRTUAL_HOST=website-mano.localhost,mano.test.fabrique.social.gouv.fr,mano.sesan.fr

  dashboard:
    build: ./dashboard
    volumes:
      - ./dashboard:/app
    environment:
      - NODE_ENV=production
      - VIRTUAL_HOST=espace-mano.localhost,espace-mano.test.fabrique.social.gouv.fr,espace-mano.sesan.fr
      - PORT=3000

  api:
    build: ./api
    volumes:
      - ./api:/app
    environment:
      - NODE_ENV=production
      - VIRTUAL_HOST=api-mano.localhost,api-mano.test.fabrique.social.gouv.fr,api-mano.sesan.fr
      - PORT=3000
      - DEPLOY_KEY=/run/secrets/deploy_key
      - PGHOST=host.docker.internal
      - PGUSER=/run/secrets/pguser
      - PGPASSWORD=/run/secrets/pgpassword
      - PGDATABASE=mano
    extra_hosts:
      - "host.docker.internal:host-gateway"
    secrets:
      - deploy_key
      - pgpassword
      - pguser

  metabase:
    image: metabase/metabase
    environment:
      - VIRTUAL_HOST=metabase-mano.localhost,metabase-mano.test.fabrique.social.gouv.fr,metabase-mano.sesan.fr
    volumes:
      - ./metabase:/metabase-data
    extra_hosts:
      - "host.docker.internal:host-gateway"

  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

secrets:
  deploy_key:
    file: ./secrets/deploy_key
  pgpassword:
    file: ./secrets/pgpassword
  pguser:
    file: ./secrets/pguser
