const express = require("express");
const router = express.Router();
const passport = require("passport");
const { Op } = require("sequelize");
const path = require("path");
const fs = require("fs");
const multer = require("multer");
const crypto = require("crypto");
const { z } = require("zod");
const { catchErrors } = require("../errors");
const {
  Person,
  Action,
  Comment,
  Group,
  Passage,
  Rencontre,
  Consultation,
  Treatment,
  MedicalFile,
  RelPersonPlace,
  sequelize,
} = require("../db/sequelize");
const { STORAGE_DIRECTORY } = require("../config");
const validateEncryptionAndMigrations = require("../middleware/validateEncryptionAndMigrations");
const validateUser = require("../middleware/validateUser");
const { looseUuidRegex, cryptoHexRegex, positiveIntegerRegex, detectAndLogRaceCondition } = require("../utils");
const { capture } = require("../sentry");

// Return the basedir to store persons' documents.
function personDocumentBasedir(userOrganisation, personId) {
  const basedir = STORAGE_DIRECTORY ? path.join(STORAGE_DIRECTORY, "uploads") : path.join(__dirname, "../../uploads");
  console.log(path.join(basedir, `${userOrganisation}`, "persons", `${personId}`));
  return path.join(basedir, `${userOrganisation}`, "persons", `${personId}`);
}

// Upload a document for a person.
router.post(
  "/:id/document",
  passport.authenticate("user", { session: false, failWithError: true }),
  validateUser(["admin", "normal"]),
  catchErrors(async (req, res, next) => {
    try {
      z.object({
        id: z.string().regex(looseUuidRegex),
      }).parse(req.params);
    } catch (e) {
      capture("Invalid request in document creation", { extra: { e, params: req.params }, user: req.user });
      return res.status(400).send({ ok: false, error: "Invalid request" });
    }
    next();
  }),
  // Use multer to handle the file upload.
  multer({
    storage: multer.diskStorage({
      destination: (req, _file, cb) => {
        // dir is safe since it's generated by the userOrganisation and personId that has been validated.
        const dir = personDocumentBasedir(req.user.organisation, req.params.id);
        if (!fs.existsSync(dir)) {
          fs.mkdirSync(dir, { recursive: true });
        }
        cb(null, dir);
      },
      filename: (_req, _file, cb) => {
        return cb(null, crypto.randomBytes(30).toString("hex"));
      },
    }),
  }).single("file"),
  catchErrors(async (req, res) => {
    const { file } = req;
    // Send back file information.
    res.send({
      ok: true,
      data: {
        originalname: file.originalname,
        filename: file.filename,
        size: file.size,
        encoding: file.encoding,
        mimetype: file.mimetype,
      },
    });
  })
);

// Download a file for a person by its filename.
router.get(
  "/:id/document/:filename",
  passport.authenticate("user", { session: false, failWithError: true }),
  validateUser(["admin", "normal"]),
  catchErrors(async (req, res, next) => {
    try {
      z.object({
        id: z.string().regex(looseUuidRegex),
        filename: z.string().regex(cryptoHexRegex),
      }).parse(req.params);
    } catch (e) {
      const error = new Error(`Invalid request in document get: ${e}`);
      error.status = 400;
      return next(error);
    }
    // dir and file are safe since it's generated by the userOrganisation, personId and filename that has been validated.
    const dir = personDocumentBasedir(req.user.organisation, req.params.id);
    const file = path.join(dir, req.params.filename);
    if (!fs.existsSync(file)) {
      res.status(404).send({ ok: false, error: "Désolé, le fichier n'est plus disponible." });
    } else {
      res.sendFile(file);
    }
  })
);

// Delete a file for a person by its filename.
router.delete(
  "/:id/document/:filename",
  passport.authenticate("user", { session: false, failWithError: true }),
  validateUser(["admin", "normal"]),
  catchErrors(async (req, res, next) => {
    try {
      z.object({
        id: z.string().regex(looseUuidRegex),
        filename: z.string().regex(cryptoHexRegex),
      }).parse(req.params);
    } catch (e) {
      const error = new Error(`Invalid request in document delete: ${e}`);
      error.status = 400;
      return next(error);
    }
    // dir and file are safe since it's generated by the userOrganisation, personId and filename that has been validated.
    const dir = personDocumentBasedir(req.user.organisation, req.params.id);
    const file = path.join(dir, req.params.filename);
    if (!fs.existsSync(file)) {
      // if it is not found, it might not be deleted but it's still in the database, so we return ok.
      res.send({ ok: true });
    } else {
      fs.unlinkSync(file);
      res.send({ ok: true });
    }
  })
);

router.post(
  "/import",
  passport.authenticate("user", { session: false, failWithError: true }),
  validateUser("admin"),
  validateEncryptionAndMigrations,
  catchErrors(async (req, res, next) => {
    try {
      z.object({
        personsToImport: z.array(
          z.object({
            _id: z.optional(z.string().regex(looseUuidRegex)),
            encrypted: z.string(),
            encryptedEntityKey: z.string(),
          })
        ),
        medicalFilesToImport: z.array(
          z.object({
            encrypted: z.string(),
            encryptedEntityKey: z.string(),
          })
        ),
      }).parse(req.body);
    } catch (e) {
      const error = new Error(`Invalid request in person import: ${e}`);
      error.status = 400;
      return next(error);
    }

    await sequelize.transaction(async (tx) => {
      const persons = req.body.personsToImport.map((p) => {
        const person = {
          _id: p._id,
          encrypted: p.encrypted,
          encryptedEntityKey: p.encryptedEntityKey,
          organisation: req.user.organisation,
          user: req.user._id,
        };
        return person;
      });
      await Person.bulkCreate(persons, { transaction: tx });
      const medicalFiles = req.body.medicalFilesToImport.map((p) => {
        const medicalFile = {
          encrypted: p.encrypted,
          encryptedEntityKey: p.encryptedEntityKey,
          organisation: req.user.organisation,
          user: req.user._id,
        };
        return medicalFile;
      });
      await MedicalFile.bulkCreate(medicalFiles, { transaction: tx });
    });

    return res.status(200).send({
      ok: true,
    });
  })
);

router.post(
  "/",
  passport.authenticate("user", { session: false, failWithError: true }),
  validateUser(["admin", "normal", "restricted-access"]),
  validateEncryptionAndMigrations,
  catchErrors(async (req, res, next) => {
    try {
      z.object({
        encrypted: z.string(),
        encryptedEntityKey: z.string(),
      }).parse(req.body);
    } catch (e) {
      const error = new Error(`Invalid request in person creation: ${e}`);
      error.status = 400;
      return next(error);
    }

    const data = await Person.create(
      {
        organisation: req.user.organisation,
        encrypted: req.body.encrypted,
        encryptedEntityKey: req.body.encryptedEntityKey,
      },
      { returning: true }
    );
    return res.status(200).send({
      ok: true,
      data: {
        _id: data._id,
        encrypted: data.encrypted,
        encryptedEntityKey: data.encryptedEntityKey,
        organisation: data.organisation,
        createdAt: data.createdAt,
        updatedAt: data.updatedAt,
        deletedAt: data.deletedAt,
      },
    });
  })
);

router.get(
  "/",
  passport.authenticate("user", { session: false, failWithError: true }),
  validateUser(["admin", "normal", "restricted-access", "stats-only"]),
  catchErrors(async (req, res, next) => {
    try {
      z.object({
        limit: z.optional(z.string().regex(positiveIntegerRegex)),
        page: z.optional(z.string().regex(positiveIntegerRegex)),
        after: z.optional(z.string().regex(positiveIntegerRegex)),
        withDeleted: z.optional(z.enum(["true", "false"])),
      }).parse(req.query);
    } catch (e) {
      const error = new Error(`Invalid request in person get: ${e}`);
      error.status = 400;
      return next(error);
    }
    const { limit, page, after, withDeleted } = req.query;

    const query = {
      where: { organisation: req.user.organisation },
      order: [["_id", "DESC"]],
    };

    const total = await Person.count(query);
    if (limit) query.limit = Number(limit);
    if (page) query.offset = Number(page) * limit;
    if (withDeleted === "true") query.paranoid = false;
    if (after && !isNaN(Number(after)) && withDeleted === "true") {
      query.where[Op.or] = [{ updatedAt: { [Op.gte]: new Date(Number(after)) } }, { deletedAt: { [Op.gte]: new Date(Number(after)) } }];
    } else if (after && !isNaN(Number(after))) {
      query.where.updatedAt = { [Op.gte]: new Date(Number(after)) };
    }

    const data = await Person.findAll({
      ...query,
      attributes: ["_id", "encrypted", "encryptedEntityKey", "createdAt", "updatedAt", "deletedAt"],
    });

    return res.status(200).send({
      ok: true,
      hasMore: data.length === Number(limit),
      data: data.map((person) => person.toJSON()),
      total,
    });
  })
);

router.get(
  "/:_id",
  passport.authenticate("user", { session: false, failWithError: true }),
  validateUser(["admin", "normal", "restricted-access"]),
  catchErrors(async (req, res, next) => {
    try {
      z.object({
        _id: z.string().regex(looseUuidRegex),
      }).parse(req.params);
    } catch (e) {
      const error = new Error(`Invalid request in person get by id: ${e}`);
      error.status = 400;
      return next(error);
    }

    const query = { where: { _id: req.params._id, organisation: req.user.organisation } };
    const person = await Person.findOne({
      ...query,
      attributes: ["_id", "encrypted", "encryptedEntityKey", "createdAt", "updatedAt", "deletedAt"],
    });

    if (!person) {
      return res.status(404).send({ ok: false, error: "Person not found" });
    }

    return res.status(200).send({
      ok: true,
      data: person.toJSON(),
    });
  })
);

router.put(
  "/:_id",
  passport.authenticate("user", { session: false, failWithError: true }),
  validateUser(["admin", "normal", "restricted-access"]),
  validateEncryptionAndMigrations,
  catchErrors(async (req, res, next) => {
    try {
      z.object({
        params: z.object({
          _id: z.string().regex(looseUuidRegex),
        }),
        body: z.object({
          encrypted: z.string(),
          encryptedEntityKey: z.string(),
        }),
      }).parse(req);
    } catch (e) {
      const error = new Error(`Invalid request in person put: ${e}`);
      error.status = 400;
      return next(error);
    }

    const query = { where: { _id: req.params._id, organisation: req.user.organisation } };
    const person = await Person.findOne(query);
    if (!person) return res.status(404).send({ ok: false, error: "Not Found" });

    // Check for race condition before updating
    const clientUpdatedAt = req.headers["x-race-detection-original-updated-at"];
    const component = req.headers["x-race-detection-component"];

    if (clientUpdatedAt) {
      detectAndLogRaceCondition({
        entityType: "person",
        entityId: req.params._id,
        clientUpdatedAt,
        currentEntity: person,
        user: req.user,
        req,
        component,
      });
    }

    const { encrypted, encryptedEntityKey } = req.body;
    const updatePerson = {
      encrypted: encrypted,
      encryptedEntityKey: encryptedEntityKey,
      updatedBy: req.user._id,
    };

    await Person.update(updatePerson, query, { silent: false });
    const newPerson = await Person.findOne(query);

    res.status(200).send({
      ok: true,
      data: {
        _id: newPerson._id,
        encrypted: newPerson.encrypted,
        encryptedEntityKey: newPerson.encryptedEntityKey,
        organisation: newPerson.organisation,
        createdAt: newPerson.createdAt,
        updatedAt: newPerson.updatedAt,
        deletedAt: newPerson.deletedAt,
      },
    });
  })
);

router.delete(
  "/:_id",
  passport.authenticate("user", { session: false, failWithError: true }),
  validateUser(["admin", "normal"]),
  catchErrors(async (req, res, next) => {
    try {
      z.object({ _id: z.string().regex(looseUuidRegex) }).parse(req.params);
    } catch (e) {
      const error = new Error(`Invalid request in person delete: ${e}`);
      error.status = 400;
      return next(error);
    }
    const arraysOfItemsToTransfer = ["actionsToTransfer", "commentsToTransfer"];
    for (const key of arraysOfItemsToTransfer) {
      try {
        z.array(
          z.object({
            _id: z.string().regex(looseUuidRegex),
            encrypted: z.string(),
            encryptedEntityKey: z.string(),
          })
        ).parse(req.body[key]);
      } catch (e) {
        const error = new Error(`Invalid request in person delete ${key}: ${e}`);
        error.status = 400;
        return next(error);
      }
    }
    const arraysOfIdsToDelete = [
      "actionIdsToDelete",
      "commentIdsToDelete",
      "passageIdsToDelete",
      "rencontreIdsToDelete",
      "consultationIdsToDelete",
      "treatmentIdsToDelete",
      "medicalFileIdsToDelete",
      "relsPersonPlaceIdsToDelete",
    ];
    for (const key of arraysOfIdsToDelete) {
      try {
        z.array(z.string().regex(looseUuidRegex)).parse(req.body[key]);
      } catch (e) {
        const error = new Error(`Invalid request in person delete ${key}: ${e}`);
        error.status = 400;
        return next(error);
      }
    }
    try {
      z.optional(z.string().regex(looseUuidRegex)).parse(req.body.groupIdToDelete);
    } catch (e) {
      const error = new Error(`Invalid request in person delete groupIdToDelete: ${e}`);
      error.status = 400;
      return next(error);
    }
    try {
      z.optional(
        z.object({
          _id: z.string().regex(looseUuidRegex),
          encrypted: z.string(),
          encryptedEntityKey: z.string(),
        })
      ).parse(req.body.groupToUpdate);
    } catch (e) {
      const error = new Error(`Invalid request in person delete groupToUpdate: ${e}`);
      error.status = 400;
      return next(error);
    }

    await sequelize.transaction(async (tx) => {
      const {
        groupToUpdate,
        groupIdToDelete,
        actionsToTransfer,
        commentsToTransfer,
        actionIdsToDelete,
        commentIdsToDelete,
        passageIdsToDelete,
        rencontreIdsToDelete,
        consultationIdsToDelete,
        treatmentIdsToDelete,
        medicalFileIdsToDelete,
        relsPersonPlaceIdsToDelete,
      } = req.body;

      let person = await Person.findOne({ where: { _id: req.params._id, organisation: req.user.organisation } });
      if (person) {
        await Person.update(
          { deletedBy: req.user._id, updatedBy: req.user._id },
          { where: { _id: req.params._id, organisation: req.user.organisation } },
          { silent: true, transaction: tx }
        );
        await person.destroy({ transaction: tx });
      }

      for (let { encrypted, encryptedEntityKey, _id } of actionsToTransfer) {
        await Action.update({ encrypted, encryptedEntityKey }, { where: { _id, organisation: req.user.organisation }, transaction: tx });
      }
      for (let { encrypted, encryptedEntityKey, _id } of commentsToTransfer) {
        await Comment.update({ encrypted, encryptedEntityKey }, { where: { _id, organisation: req.user.organisation }, transaction: tx });
      }
      if (groupToUpdate) {
        await Group.update(groupToUpdate, { where: { _id: groupToUpdate._id, organisation: req.user.organisation }, transaction: tx });
      }
      if (groupIdToDelete) {
        await Group.destroy({ where: { _id: groupIdToDelete, organisation: req.user.organisation }, transaction: tx });
      }
      if (actionIdsToDelete?.length > 0) {
        await Action.destroy({
          where: {
            _id: { [Op.in]: actionIdsToDelete },
            organisation: req.user.organisation,
          },
          transaction: tx,
        });
      }

      if (commentIdsToDelete?.length > 0) {
        await Comment.destroy({
          where: {
            _id: { [Op.in]: commentIdsToDelete },
            organisation: req.user.organisation,
          },
          transaction: tx,
        });
      }

      if (passageIdsToDelete?.length > 0) {
        await Passage.destroy({
          where: {
            _id: { [Op.in]: passageIdsToDelete },
            organisation: req.user.organisation,
          },
          transaction: tx,
        });
      }

      if (rencontreIdsToDelete?.length > 0) {
        await Rencontre.destroy({
          where: {
            _id: { [Op.in]: rencontreIdsToDelete },
            organisation: req.user.organisation,
          },
          transaction: tx,
        });
      }

      if (consultationIdsToDelete?.length > 0) {
        await Consultation.destroy({
          where: {
            _id: { [Op.in]: consultationIdsToDelete },
            organisation: req.user.organisation,
          },
          transaction: tx,
        });
      }

      if (treatmentIdsToDelete?.length > 0) {
        await Treatment.destroy({
          where: {
            _id: { [Op.in]: treatmentIdsToDelete },
            organisation: req.user.organisation,
          },
          transaction: tx,
        });
      }

      if (medicalFileIdsToDelete?.length > 0) {
        await MedicalFile.destroy({
          where: {
            _id: { [Op.in]: medicalFileIdsToDelete },
            organisation: req.user.organisation,
          },
          transaction: tx,
        });
      }

      if (relsPersonPlaceIdsToDelete?.length > 0) {
        await RelPersonPlace.destroy({
          where: {
            _id: { [Op.in]: relsPersonPlaceIdsToDelete },
            organisation: req.user.organisation,
          },
          transaction: tx,
        });
      }
    });

    res.status(200).send({ ok: true });
  })
);

module.exports = router;
