#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

if sh -c ': >/dev/tty' >/dev/null 2>/dev/null; then exec </dev/tty; npm run node-talisman --githook pre-commit -i; else npm run node-talisman --githook pre-commit; fi
