name: Tests - Expo Vitest
on:
  pull_request:
    branches: [main]
    paths:
      - "expo/**"
      - ".github/workflows/expo-test.yml"
  push:
    branches: [main]
    paths:
      - "expo/**"

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install expo dependencies
        run: yarn --cwd ./expo --immutable

      - name: Run Expo vitest
        run: yarn --cwd ./expo test
